"""empty message

Revision ID: 9b0081b25fc1
Revises: dae0234b38fa
Create Date: 2020-08-19 10:24:08.406611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0081b25fc1'
down_revision = 'dae0234b38fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'availability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('availability', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
